definitions:
  domain.Booking:
    properties:
      conferenceLink:
        type: string
      createdAt:
        type: string
      id:
        type: string
      slotId:
        type: string
      status:
        $ref: '#/definitions/domain.BookingStatus'
      userId:
        type: string
    type: object
  domain.BookingStatus:
    enum:
    - active
    - cancelled
    type: string
    x-enum-varnames:
    - BookingStatusActive
    - BookingStatusCancelled
  domain.Pagination:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  domain.Role:
    enum:
    - admin
    - user
    type: string
    x-enum-varnames:
    - RoleAdmin
    - RoleUser
  domain.Room:
    properties:
      capacity:
        type: integer
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  domain.Schedule:
    properties:
      createdAt:
        type: string
      daysOfWeek:
        items:
          type: integer
        type: array
      endTime:
        type: string
      id:
        type: string
      roomId:
        type: string
      startTime:
        type: string
    type: object
  domain.Slot:
    properties:
      end:
        type: string
      id:
        type: string
      roomId:
        type: string
      start:
        type: string
    type: object
  domain.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      role:
        $ref: '#/definitions/domain.Role'
    type: object
  handlers.bookingResponse:
    properties:
      booking:
        $ref: '#/definitions/domain.Booking'
    type: object
  handlers.bookingsResponse:
    properties:
      bookings:
        items:
          $ref: '#/definitions/domain.Booking'
        type: array
      pagination:
        $ref: '#/definitions/domain.Pagination'
    type: object
  handlers.createBookingRequest:
    properties:
      createConferenceLink:
        type: boolean
      slotId:
        type: string
    type: object
  handlers.createRoomRequest:
    properties:
      capacity:
        type: integer
      description:
        type: string
      name:
        type: string
    type: object
  handlers.dummyLoginRequest:
    properties:
      role:
        type: string
    type: object
  handlers.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  handlers.registerRequest:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  handlers.roomResponse:
    properties:
      room:
        $ref: '#/definitions/domain.Room'
    type: object
  handlers.roomsResponse:
    properties:
      rooms:
        items:
          $ref: '#/definitions/domain.Room'
        type: array
    type: object
  handlers.scheduleResponse:
    properties:
      schedule:
        $ref: '#/definitions/domain.Schedule'
    type: object
  handlers.slotsResponse:
    properties:
      slots:
        items:
          $ref: '#/definitions/domain.Slot'
        type: array
    type: object
  handlers.tokenResponse:
    properties:
      token:
        type: string
    type: object
  handlers.userResponse:
    properties:
      user:
        $ref: '#/definitions/domain.User'
    type: object
info:
  contact: {}
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Service root
      tags:
      - Health
  /_info:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Service info
      tags:
      - Health
  /bookings/{bookingId}/cancel:
    post:
      parameters:
      - description: booking id
        in: path
        name: bookingId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.bookingResponse'
      security:
      - BearerAuth: []
      summary: Отменить бронь
      tags:
      - Bookings
  /bookings/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: booking
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.createBookingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.bookingResponse'
        "409":
          description: Conflict
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Создать бронь
      tags:
      - Bookings
  /bookings/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.bookingsResponse'
      security:
      - BearerAuth: []
      summary: Список всех броней
      tags:
      - Bookings
  /bookings/my:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.bookingsResponse'
      security:
      - BearerAuth: []
      summary: Список броней текущего пользователя
      tags:
      - Bookings
  /dummyLogin:
    post:
      consumes:
      - application/json
      parameters:
      - description: role
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.dummyLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.tokenResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Получить тестовый JWT по роли
      tags:
      - Auth
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.tokenResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Авторизация по email и паролю
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: register
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.userResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Регистрация пользователя
      tags:
      - Auth
  /rooms/{roomId}/schedule/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: room id
        in: path
        name: roomId
        required: true
        type: string
      - description: schedule
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Schedule'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.scheduleResponse'
        "409":
          description: Conflict
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Создать расписание переговорки
      tags:
      - Schedules
  /rooms/{roomId}/slots/list:
    get:
      parameters:
      - description: room id
        in: path
        name: roomId
        required: true
        type: string
      - description: date
        in: query
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.slotsResponse'
      security:
      - BearerAuth: []
      summary: Список доступных слотов
      tags:
      - Slots
  /rooms/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: room
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.createRoomRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.roomResponse'
        "403":
          description: Forbidden
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Создать переговорку
      tags:
      - Rooms
  /rooms/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.roomsResponse'
      security:
      - BearerAuth: []
      summary: Список переговорок
      tags:
      - Rooms
swagger: "2.0"
